### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by geocolumbus** [pffy/googledocs-addon-wikitable#2]
I read the README file several times, and I must be dense. I have no idea how to install this!

**Comment by pffy** [comment]
Thank you for catching that omission. No, you are not dense. The documentation for this add-on is incomplete. Installation instructions have just been added to the README file.
  + https://github.com/pffy/googledocs-addon-wikitable#install

Much Appreciated,
-- The Pffy Authors

**Comment by pffy** [comment]
@geocolumbus Thank you for your interest in WikiTableWorks. You can install an advanced release version in the Google Chrome Web Store.

+ https://chrome.google.com/webstore/detail/wikitableworks/fcidnbkcodoajhfbcaefikfemlggcpfp

[![chromewebstore_badgewborder_v2_340x96](https://cloud.githubusercontent.com/assets/7258373/6788162/ee497942-d154-11e4-934d-ef386061181d.png)](https://chrome.google.com/webstore/detail/wikitableworks/fcidnbkcodoajhfbcaefikfemlggcpfp)
